require "user.options"
require "user.plugins"
require "user.impatient"
require "user.alpha"
require "user.colorscheme"
require "user.toggleterm"
-- require "user.nvim-tree"
require "user.neo-tree"
require "user.indentline"
require "user.bufferline"
require "user.telescope"
require "user.gitsigns"
require "user.comment"
require "user.coc"
require "user.keymaps"
